# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

on: push

permissions:
  packages: write
    

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    concurrency:
      group: build
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
          tags: ghcr.io/${{ env.REPOSITORY }}:${{ github.sha }}
